//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class PositionDirectMsg : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/PositionDirect";
        public override string RosMessageName => k_RosMessageName;

        //  Message used to send position direct commands to one or multiple joints
        //  names: it can contain the names of the joints to send the position command to. If left empty, a position value for all the joints available must be provided
        //  positions: it must contain a position value for each name listed in the names vector or for every joint if the names vector is left empty
        public string[] names;
        public double[] positions;

        public PositionDirectMsg()
        {
            this.names = new string[0];
            this.positions = new double[0];
        }

        public PositionDirectMsg(string[] names, double[] positions)
        {
            this.names = names;
            this.positions = positions;
        }

        public static PositionDirectMsg Deserialize(MessageDeserializer deserializer) => new PositionDirectMsg(deserializer);

        private PositionDirectMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.positions, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.positions);
            serializer.Write(this.positions);
        }

        public override string ToString()
        {
            return "PositionDirectMsg: " +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\npositions: " + System.String.Join(", ", positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
