//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class GetControlModesResponse : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/GetControlModes";
        public override string RosMessageName => k_RosMessageName;

        //  modes: it will cotain the control modes for the joints specified in "names" or for all them if "names" is empty
        //  response: a brief string used to signal the state of the result of the request
        //  opt_descr: An optional human readable description of the result of the request
        public string[] modes;
        public string response = "NOT_SPECIFIED";
        public string opt_descr;

        public GetControlModesResponse()
        {
            this.modes = new string[0];
            this.opt_descr = "";
        }

        public GetControlModesResponse(string[] modes, string response, string opt_descr)
        {
            this.modes = modes;
            this.response = response;
            this.opt_descr = opt_descr;
        }

        public static GetControlModesResponse Deserialize(MessageDeserializer deserializer) => new GetControlModesResponse(deserializer);

        private GetControlModesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.modes, deserializer.ReadLength());
            deserializer.Read(out this.response);
            deserializer.Read(out this.opt_descr);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.modes);
            serializer.Write(this.modes);
            serializer.Write(this.response);
            serializer.Write(this.opt_descr);
        }

        public override string ToString()
        {
            return "GetControlModesResponse: " +
            "\nmodes: " + System.String.Join(", ", modes.ToList()) +
            "\nresponse: " + response.ToString() +
            "\nopt_descr: " + opt_descr.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
