//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class GetJointsNamesRequest : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/GetJointsNames";
        public override string RosMessageName => k_RosMessageName;

        //  Service to be used to retrieve the names of a set of joints
        //  joints_indexes: it contains the indexes of the joints the user wants to get the names of. If left empty, the names of all the available joints will be returned
        public int[] joint_indexes;

        public GetJointsNamesRequest()
        {
            this.joint_indexes = new int[0];
        }

        public GetJointsNamesRequest(int[] joint_indexes)
        {
            this.joint_indexes = joint_indexes;
        }

        public static GetJointsNamesRequest Deserialize(MessageDeserializer deserializer) => new GetJointsNamesRequest(deserializer);

        private GetJointsNamesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_indexes, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_indexes);
            serializer.Write(this.joint_indexes);
        }

        public override string ToString()
        {
            return "GetJointsNamesRequest: " +
            "\njoint_indexes: " + System.String.Join(", ", joint_indexes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
