//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class GetJointsNamesResponse : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/GetJointsNames";
        public override string RosMessageName => k_RosMessageName;

        //  names: it will cotain the names for the joints specified in "indexes" or for all them if "indexes" is empty
        //  response: a brief string used to signal the state of the result of the request
        //  opt_descr: An optional human readable description of the result of the request
        public string[] names;
        public string response = "NOT_SPECIFIED";
        public string opt_descr;

        public GetJointsNamesResponse()
        {
            this.names = new string[0];
            this.opt_descr = "";
        }

        public GetJointsNamesResponse(string[] names, string response, string opt_descr)
        {
            this.names = names;
            this.response = response;
            this.opt_descr = opt_descr;
        }

        public static GetJointsNamesResponse Deserialize(MessageDeserializer deserializer) => new GetJointsNamesResponse(deserializer);

        private GetJointsNamesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.response);
            deserializer.Read(out this.opt_descr);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.Write(this.response);
            serializer.Write(this.opt_descr);
        }

        public override string ToString()
        {
            return "GetJointsNamesResponse: " +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nresponse: " + response.ToString() +
            "\nopt_descr: " + opt_descr.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
