//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class GetVelocityResponse : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/GetVelocity";
        public override string RosMessageName => k_RosMessageName;

        //  modes: it will contain the velocity for the joints specified in "names" or for all them if "names" is empty
        //  response: a brief string used to signal the state of the result of the request
        //  opt_descr: An optional human readable description of the result of the request
        public double[] velocities;
        public string response = "NOT_SPECIFIED";
        public string opt_descr;

        public GetVelocityResponse()
        {
            this.velocities = new double[0];
            this.opt_descr = "";
        }

        public GetVelocityResponse(double[] velocities, string response, string opt_descr)
        {
            this.velocities = velocities;
            this.response = response;
            this.opt_descr = opt_descr;
        }

        public static GetVelocityResponse Deserialize(MessageDeserializer deserializer) => new GetVelocityResponse(deserializer);

        private GetVelocityResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.velocities, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.response);
            deserializer.Read(out this.opt_descr);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.velocities);
            serializer.Write(this.velocities);
            serializer.Write(this.response);
            serializer.Write(this.opt_descr);
        }

        public override string ToString()
        {
            return "GetVelocityResponse: " +
            "\nvelocities: " + System.String.Join(", ", velocities.ToList()) +
            "\nresponse: " + response.ToString() +
            "\nopt_descr: " + opt_descr.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
