//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class GetVelocityRequest : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/GetVelocity";
        public override string RosMessageName => k_RosMessageName;

        //  Service to get the current velocity for a set of joints
        //  names: it can contain the names of the joints from which the velocity has to be retrieved. If left empty, the velocity of all the available joints will be returned
        public string[] names;

        public GetVelocityRequest()
        {
            this.names = new string[0];
        }

        public GetVelocityRequest(string[] names)
        {
            this.names = names;
        }

        public static GetVelocityRequest Deserialize(MessageDeserializer deserializer) => new GetVelocityRequest(deserializer);

        private GetVelocityRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
        }

        public override string ToString()
        {
            return "GetVelocityRequest: " +
            "\nnames: " + System.String.Join(", ", names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
