//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YarpControl
{
    [Serializable]
    public class SetControlModesResponse : Message
    {
        public const string k_RosMessageName = "yarp_control_msgs/SetControlModes";
        public override string RosMessageName => k_RosMessageName;

        //  response: a brief string used to signal the state of the result of the request
        //  opt_descr: An optional human readable description of the result of the request
        public string response = "NOT_SPECIFIED";
        public string opt_descr;

        public SetControlModesResponse()
        {
            this.opt_descr = "";
        }

        public SetControlModesResponse(string response, string opt_descr)
        {
            this.response = response;
            this.opt_descr = opt_descr;
        }

        public static SetControlModesResponse Deserialize(MessageDeserializer deserializer) => new SetControlModesResponse(deserializer);

        private SetControlModesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
            deserializer.Read(out this.opt_descr);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
            serializer.Write(this.opt_descr);
        }

        public override string ToString()
        {
            return "SetControlModesResponse: " +
            "\nresponse: " + response.ToString() +
            "\nopt_descr: " + opt_descr.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
